### ISSUE TITLE
从零开始学CSS之选择器

### ISSUE THREAD

**Issue by wangqiutuner** [wangqiutuner/Blog#5]
# CSS中的选择器

## 一、不同种类的CSS选择器

- **简单选择器**：通过元素类型、`class` 或 `id` 匹配一个或多个元素。
- **属性选择器**：通过 属性 / 属性值 匹配一个或多个元素。
- **伪类**：匹配处于确定状态的一个或多个元素，比如被鼠标指针悬停的元素，或当前被选中或未选中的复选框，或元素是DOM树中一父节点的第一个子节点。
- **伪元素**：匹配处于相关的确定位置的一个或多个元素，例如每个段落的第一个字，或者某个元素之前生成的内容。
- **组合器**：这里不仅仅是选择器本身，还有以有效的方式组合两个或更多的选择器用于非常特定的选择的方法。例如，你可以只选择divs的直系子节点的段落，或者直接跟在headings后面的段落。
- **多重选择器**：这些也不是单独的选择器；这个思路是将以逗号分隔开的多个选择器放在一个CSS规则下面， 以将一组声明应用于由这些选择器选择的所有元素。

## 二、简单选择器

包括类型（元素）选择器，类选择器，ID选择器，通用选择器（ `*` ），这些选择器是我们平常使用最广泛的，也是最为简单的核心选择器，这里不做过多介绍。

### 存在和值（Presence and value）属性选择器

- **`[attr]`**：该选择器选择包含 attr 属性的所有元素，不论 attr 的值为何。
- **`[attr=val]`**：该选择器仅选择 attr 属性被赋值为 val 的所有元素。
- **`[attr~=val]`**：该选择器仅选择具有 attr 属性的元素，而且要求 val 值是 attr 值包含的被空格分隔的取值列表里中的一个。

```html
<ul>
  <li data-quantity="1kg" data-vegetable>Tomatoes</li>
  <li data-quantity="700g" data-vegetable="not spicy like chili">Red pepper</li>
  <li data-quantity="2kg" data-meat>Chicken</li>
  <li data-quantity="25cl" data-vegetable="liquid">White wine</li>
</ul>
```

```css
/* 所有具有"data-vegetable"属性的元素将被应用绿色的文本颜色 */
[data-vegetable] {
  color: green
}

/* 所有具有"data-vegetable"属性且属性值刚好为"liquid"的元素将被应用金色的背景颜色 */
[data-vegetable="liquid"] {
  background-color: goldenrod;
}

/* 所有具有"data-vegetable"属性且属性值包含"spicy"的元素，
即使元素的属性中还包含其他属性值，都会被应用红色的文本颜色 */
[data-vegetable~="spicy"] {
  color: red;
}
```

结果如下：

<style>
[data-vegetable] {
  color: green
}
[data-vegetable="liquid"] {
  background-color: goldenrod;
}
[data-vegetable~="spicy"] {
  color: red;
</style>

<ul>
  <li data-quantity="1kg" data-vegetable>Tomatoes</li>
  <li data-quantity="700g" data-vegetable="not spicy like chili">Red pepper</li>
  <li data-quantity="2kg" data-meat>Chicken</li>
  <li data-quantity="25cl" data-vegetable="liquid">White wine</li>
</ul>

### 子串值（Substring value）属性选择器

匹配字符串的一部分，目前没有发现什么用途。

## 四、伪类

一个 CSS  伪类（pseudo-class） 是一个以冒号(`:`)作为前缀，被添加到一个选择器末尾的关键字，当你希望样式在特定状态下才被呈现到指定的元素时，你可以往元素的选择器后面加上对应的伪类（pseudo-class）。

**链接相关伪类：**

**`:active`**： CSS伪类匹配被用户激活的元素。它让页面能在浏览器监测到激活时给出反馈。当用鼠标交互时，它代表的是用户按下按键和松开按键之间的时间。 :active 伪类通常用来匹配tab键交互。通常用于但并不限于 `<a>` 和 `<button>` HTML元素。

这个样式可能会被后声明的其他链接相关的伪类覆盖，这些伪类包括 `:link`，`:hover`和 `:visited`。为了正常加上样式，需要把 `:active`的样式放在所有链接相关的样式后，这种链接伪类先后顺序被称为**LVHA**顺序: `:link` — `:visited` — `:hover` — `:active`。

```html
<p>这个链接在鼠标按下和松开的这段时间内会变成绿色: <a href="#">Mozilla Developer Network</a>.</p>
```

```css
a:link { color: blue } /* 未访问链接 */
a:visited { color: purple } /* 已访问链接 */
a:hover { font-weight: bold } /* 用户鼠标悬停 */
a:active { color: lime } /* 激活链接 */
```

结果如下：

<style>
a:link { color: blue } /* 未访问链接 */
a:visited { color: purple } /* 已访问链接 */
a:hover { font-weight: bold } /* 用户鼠标悬停 */
a:active { color: lime } /* 激活链接 */
</style>

<p>这个链接在鼠标按下和松开的这段时间内会变成绿色: <a href="#">Mozilla Developer Network</a>.</p>

*后序的伪类待实际应用中使用后进行扩充。*

## 五、伪元素

伪元素（Pseudo-element）跟伪类很像，但它们又有不同的地方。它们都是关键字，但这次伪元素前缀是两个冒号 (`::`) ， 同样是添加到选择器后面去选择某个元素的某个部分。

**常用的伪元素：**

**`::after`**：创建一个伪元素，作为已选中元素的最后一个子元素。通常会配合content属性来为该元素添加装饰内容。这个虚拟元素默认是行内元素。

**q_qiu**：`::` 是css3用来区分伪类和伪元素的，所以只有在ie9+才支持， IE8仅支持`:after`。

**`::before`**：创建一个伪元素，其将成为匹配选中的元素的第一个子元素。

**q_qiu**：由`::before` 和`::after` 生成的伪元素 包含在元素格式框内， 因此不能应用在替换元素上， 比如`<img>`或`<br>`元素。

## 六、组合器和选择器组

<table summary="组合器和选择器组">
    <tr>
        <th>名称</th>
        <th>组合器</th>
        <th>选择</th>
    </tr>
    <tr>
        <td>选择器组</td>
        <td>A,B</td>
        <td>匹配满足A（和/或）B的任意元素</td>
    </tr>
    <tr>
        <td>后代选择器</td>
        <td>A B</td>
        <td>匹配B元素，满足条件：B是A的后代结点（B是A的子节点，或者A的子节点的子节点）</td>
    </tr>
    <tr>
        <td>子选择器</td>
        <td>A > B</td>
        <td>匹配B元素，满足条件：B是A的直接子节点</td>
    </tr>
    <tr>
        <td>相邻兄弟选择器</td>
        <td>A + B</td>
        <td>匹配B元素，满足条件：B是A的下一个兄弟节点（AB有相同的父结点，并且B紧跟在A的后面）</td>
    </tr>
    <tr>
        <td>通用兄弟选择器</td>
        <td>A ~ B</td>
        <td>匹配B元素，满足条件：B是A之后的任意一个兄弟节点（AB有相同的父节点，B在A之后，但不一定是紧挨着A））</td>
    </tr>
</table>
